### ISSUE TITLE
Modal/.ola_modal-content padding

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#76]
when .ola_modal-content has only one child it does not apply the padding styles.

<img width="989" alt="Captura de pantalla 2020-02-17 a las 16 28 39" src="https://user-images.githubusercontent.com/29247073/74667056-ec588f00-51a2-11ea-8e44-5b4741ca655a.png">
<img width="1074" alt="Captura de pantalla 2020-02-17 a las 16 28 56" src="https://user-images.githubusercontent.com/29247073/74667068-f11d4300-51a2-11ea-9a98-ada3a57bd91b.png">

**Comment by oscarotero** [comment]
The second image is right. The extra padding top and bottom is applied only if the element is the first or last child (this is to cover cases of modals without headers or footers).
The padding in the first image is because the content is not a direct child of modal (it's in a div, a form or something like that). If you are using a form, it should be used in the whole modal (including the header and footer).
